// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDapQVR29oLY2jBZOd1FB93pESsbLvDDY0',
    appId: '1:229629754692:web:67b3d8df292b9e9bca6b11',
    messagingSenderId: '229629754692',
    projectId: 'socialmediaapp-96049',
    authDomain: 'socialmediaapp-96049.firebaseapp.com',
    storageBucket: 'socialmediaapp-96049.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbjeNBzAp8CeEUnHMbSkvaksHByd_uPO0',
    appId: '1:229629754692:android:a67ef0dbe9054c00ca6b11',
    messagingSenderId: '229629754692',
    projectId: 'socialmediaapp-96049',
    storageBucket: 'socialmediaapp-96049.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-DZtPb_L4tc21SMLN3FG6h1sGfMcJJVo',
    appId: '1:229629754692:ios:157b7b2cdc6bab7eca6b11',
    messagingSenderId: '229629754692',
    projectId: 'socialmediaapp-96049',
    storageBucket: 'socialmediaapp-96049.firebasestorage.app',
    iosBundleId: 'com.example.socialmediaapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-DZtPb_L4tc21SMLN3FG6h1sGfMcJJVo',
    appId: '1:229629754692:ios:157b7b2cdc6bab7eca6b11',
    messagingSenderId: '229629754692',
    projectId: 'socialmediaapp-96049',
    storageBucket: 'socialmediaapp-96049.firebasestorage.app',
    iosBundleId: 'com.example.socialmediaapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDapQVR29oLY2jBZOd1FB93pESsbLvDDY0',
    appId: '1:229629754692:web:cd922f98a92d357fca6b11',
    messagingSenderId: '229629754692',
    projectId: 'socialmediaapp-96049',
    authDomain: 'socialmediaapp-96049.firebaseapp.com',
    storageBucket: 'socialmediaapp-96049.firebasestorage.app',
  );
}
